import './globals.css'
import type { Metadata } from 'next'
import {
  MetaRootPageTitle as RootTitle,
  MetaTitleTemplate as TitleTemplate
} from '@/app/_components/MetaTitles'
import Header from '@/app/_components/Header'
import Footer from '@/app/_components/Footer'
import { useEffect } from 'react'

export const metadata: Metadata = {
  title: `${RootTitle} | ${TitleTemplate}`,
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  useEffect(() => {
    const head = document.getElementsByTagName('head')[0] as HTMLElement
    const scriptUrl = document.createElement('script')
    scriptUrl.src = 'https://sdk.form.run/js/v2/embed.js'
    head.appendChild(scriptUrl)
    return () => {
      // コンポーネントがアンマウントされる際にHeadからスクリプトのクリーンアップを行う
      head.removeChild(scriptUrl)
    }
  }, [])

  return (
    <html lang="ja">
      <body>
        <Header />
        <main className="">{children}</main>
        <Footer />
      </body>
    </html>
  )
}
