import './globals.css'
import type { Metadata } from 'next'
import {
  MetaRootPageTitle as RootTitle,
  MetaTitleTemplate as TitleTemplate
} from '@/app/_components/MetaTitles'
import Header from '@/app/_components/Header'
import Footer from '@/app/_components/Footer'

export const metadata: Metadata = {
  title: `${RootTitle} | ${TitleTemplate}`,
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>
        <Header />
        <main className="">{children}</main>
        <Footer />
      </body>
    </html>
  )
}
